name: Publish latest image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/tool-frontend:latest

      - name: Push the image
        run: docker push ${{secrets.DOCKER_USER}}/tool-frontend
